apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: roboshop
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJ1c2VybmFtZSI6ICJzb3dt eWE0ODAiLCAicGFzc3dvcmQiOiAiZGNrcl9wYXRfRzlnTTdvbS1QYUVBN0VINzRlRmt4d0RfYUJrIiwgImVtYWlsIjogImtv bmRhcGlsbGlzb3dteWE0ODBAZ21haWwuY29tIiwgImF1dGgiOiAiYVc1bWJHOWhaR1Z6YzNWc0xYQnZkWE0yWVdOdFgyVnlkR2xtYVdOaG JtRnRaV05qYjNWdWRISjFiR1Z5YVc1blgybHVkR2xqWVdOdmJuUmxabWx1WldScGMybDZaV1F5WkdGMFpTNWxkWE5wYlhCcGJtYyJ9fX0=
